receivers:
  otlp:
    protocols:
      http:

processors:
 batch:

exporters:
 otlp:
   endpoint: http://tempo:55681/v1/trace

service:
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch]
     exporters: [otlp]